version: '3'

services:
  web:
    build:
      context: nginx
    environment:
      - FLASK_SERVER_ADDR=backend:9091
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build:
      context: flask
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - AWS_DYNAMODB_ENDPOINT=${AWS_DYNAMODB_ENDPOINT}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./flask:/src
    depends_on:
      -  dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    volumes:
      - ./dynamodb:/home/dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."